import { z } from "zod";

/**
 * Risk classification returned by the model.
 */
export const RiskLevelSchema = z.enum([
  "SAFE",
  "MISLEADING",
  "HIGH_RISK_HOAX",
  "FINANCIAL_SCAM",
  "HEALTH_MISINFORMATION",
]);
export type RiskLevel = z.infer<typeof RiskLevelSchema>;

/**
 * A warm, family-friendly WhatsApp-style correction message,
 * written back in the same dialect / script / transliteration
 * style as the original message.
 */
export const CounterReplySchema = z.object({
  text: z.string().min(1, "counter_reply.text must not be empty"),
  script: z.string().min(1, "counter_reply.script must not be empty"),
  tone_style: z.string().min(1, "counter_reply.tone_style must not be empty"),
});
export type CounterReply = z.infer<typeof CounterReplySchema>;

/**
 * Exactly what we ask Claude to produce via forced tool calling.
 * (Everything the MODEL is responsible for generating.)
 */
export const ClaudeAnalysisSchema = z.object({
  detected_language: z.string().min(1, "detected_language must not be empty"),
  is_code_mixed: z.boolean(),
  risk_level: RiskLevelSchema,
  confidence_score: z
    .number()
    .min(0, "confidence_score must be >= 0")
    .max(1, "confidence_score must be <= 1"),
  reasoning: z.string().min(1, "reasoning must not be empty"),
  counter_reply: CounterReplySchema,
});
export type ClaudeAnalysis = z.infer<typeof ClaudeAnalysisSchema>;

/**
 * Server-side observability metadata (PRISM = our governance/audit layer).
 * This is computed by our backend, NOT generated by the model.
 */
export const PrismTraceSchema = z.object({
  latency_ms: z.number().nonnegative(),
  model_version: z.string().min(1),
  flagged_for_audit: z.boolean(),
});
export type PrismTrace = z.infer<typeof PrismTraceSchema>;

/**
 * Full response shape returned by POST /api/analyze.
 */
export const DetectionResultSchema = ClaudeAnalysisSchema.extend({
  prism_trace: PrismTraceSchema,
});
export type DetectionResult = z.infer<typeof DetectionResultSchema>;

/**
 * Expected request body for POST /api/analyze.
 */
export const AnalyzeRequestSchema = z.object({
  message: z
    .string()
    .min(1, "message must not be empty")
    .max(4000, "message must be 4000 characters or fewer"),
});
export type AnalyzeRequest = z.infer<typeof AnalyzeRequestSchema>;

/**
 * Standard error response shape for /api/analyze.
 */
export interface AnalyzeErrorResponse {
  error: string;
  details?: unknown;
}
